### ISSUE TITLE
Convert on release of Enter key

### ISSUE THREAD

**Issue by magarenzo** [SygWave/reconstruct.js#1]
Either keep `<textarea>` and implement a way to listen for or read until (the release of) the Enter key, OR change to `<input>` which is manipulated to be multiple lines and add event listener

**Comment by ccsCoder** [comment]
Hi @magarenzo ,
I want to try. Could you please assign this to me ?

**Comment by magarenzo** [comment]
> Hi @magarenzo ,
> I want to try. Could you please assign this to me ?

Hi @ccsCoder,

Done! You're assigned 😎

Let us know what you think. Looking forward to seeing your take on this! 🚀 

Best,
Michael

P.S. There have been some updates since your initial fork

**Comment by magarenzo** [comment]
Hi @ccsCoder,

I ended up pushing a solution to production in which I just added an event listener to the input element.

Please still feel free to let us know what you think! Thanks for your interest 😄 

Best,
Michael
